TT_SERVICES = [
    'ts-assurance-service',
    'ts-auth-service',
    'ts-basic-service',
    'ts-cancel-service',
    'ts-config-service',
    'ts-contacts-service',
    'ts-food-map-service',
    'ts-food-service',
    'ts-inside-payment-service',
    'ts-notification-service',
    'ts-order-other-service',
    'ts-order-service',
    'ts-payment-service',
    'ts-preserve-service',
    'ts-price-service',
    'ts-route-plan-service',
    'ts-route-service',
    'ts-seat-service',
    'ts-security-service',
    'ts-station-service',
    'ts-ticketinfo-service',
    'ts-train-service',
    'ts-travel-plan-service',
    'ts-travel-service',
    'ts-travel2-service',
    'ts-user-service',
    'ts-verification-code-service',
]

TT_SERVICE2NID = {name: idx for idx, name in enumerate(TT_SERVICES)}
TT_NUM_NODES = len(TT_SERVICES)

TT_METRICS = [
    'cpu_usage_system',
    'cpu_usage_total',
    'cpu_usage_user',
    'memory_usage',
    'memory_working_set',
    'rx_bytes',
    'tx_bytes',
]

FAULT_CONTAINER_TO_SERVICE = {
    'dockercomposemanifests_ts-assurance-service_1': 'ts-assurance-service',
    'dockercomposemanifests_ts-auth-service_1': 'ts-auth-service',
    'dockercomposemanifests_ts-basic-service_1': 'ts-basic-service',
    'dockercomposemanifests_ts-cancel-service_1': 'ts-cancel-service',
    'dockercomposemanifests_ts-config-service_1': 'ts-config-service',
    'dockercomposemanifests_ts-contacts-service_1': 'ts-contacts-service',
    'dockercomposemanifests_ts-food-map-service_1': 'ts-food-map-service',
    'dockercomposemanifests_ts-food-service_1': 'ts-food-service',
    'dockercomposemanifests_ts-inside-payment-service_1': 'ts-inside-payment-service',
    'dockercomposemanifests_ts-notification-service_1': 'ts-notification-service',
    'dockercomposemanifests_ts-order-other-service_1': 'ts-order-other-service',
    'dockercomposemanifests_ts-order-service_1': 'ts-order-service',
    'dockercomposemanifests_ts-payment-service_1': 'ts-payment-service',
    'dockercomposemanifests_ts-preserve-service_1': 'ts-preserve-service',
    'dockercomposemanifests_ts-price-service_1': 'ts-price-service',
    'dockercomposemanifests_ts-route-plan-service_1': 'ts-route-plan-service',
    'dockercomposemanifests_ts-route-service_1': 'ts-route-service',
    'dockercomposemanifests_ts-seat-service_1': 'ts-seat-service',
    'dockercomposemanifests_ts-security-service_1': 'ts-security-service',
    'dockercomposemanifests_ts-station-service_1': 'ts-station-service',
    'dockercomposemanifests_ts-ticketinfo-service_1': 'ts-ticketinfo-service',
    'dockercomposemanifests_ts-train-service_1': 'ts-train-service',
    'dockercomposemanifests_ts-travel-plan-service_1': 'ts-travel-plan-service',
    'dockercomposemanifests_ts-travel-service_1': 'ts-travel-service',
    'dockercomposemanifests_ts-travel2-service_1': 'ts-travel2-service',
    'dockercomposemanifests_ts-user-service_1': 'ts-user-service',
    'dockercomposemanifests_ts-verification-code-service_1': 'ts-verification-code-service',
}

TT_EDGES = [
    ('ts-preserve-service', 'ts-seat-service'),
    ('ts-preserve-service', 'ts-security-service'),
    ('ts-preserve-service', 'ts-food-service'),
    ('ts-preserve-service', 'ts-order-service'),
    ('ts-preserve-service', 'ts-ticketinfo-service'),
    ('ts-preserve-service', 'ts-travel-service'),
    ('ts-preserve-service', 'ts-contacts-service'),
    ('ts-preserve-service', 'ts-notification-service'),
    ('ts-preserve-service', 'ts-user-service'),
    ('ts-preserve-service', 'ts-station-service'),
    ('ts-seat-service', 'ts-order-service'),
    ('ts-seat-service', 'ts-config-service'),
    ('ts-seat-service', 'ts-travel-service'),
    ('ts-cancel-service', 'ts-inside-payment-service'),
    ('ts-cancel-service', 'ts-order-other-service'),
    ('ts-cancel-service', 'ts-order-service'),
    ('ts-security-service', 'ts-order-other-service'),
    ('ts-security-service', 'ts-order-service'),
    ('ts-food-service', 'ts-travel-service'),
    ('ts-food-service', 'ts-food-map-service'),
    ('ts-food-service', 'ts-station-service'),
    ('ts-travel-service', 'ts-order-service'),
    ('ts-travel-service', 'ts-ticketinfo-service'),
    ('ts-travel-service', 'ts-train-service'),
    ('ts-travel-service', 'ts-route-service'),
    ('ts-inside-payment-service', 'ts-payment-service'),
    ('ts-inside-payment-service', 'ts-order-service'),
    ('ts-ticketinfo-service', 'ts-basic-service'),
    ('ts-basic-service', 'ts-route-service'),
    ('ts-basic-service', 'ts-price-service'),
    ('ts-basic-service', 'ts-train-service'),
    ('ts-basic-service', 'ts-station-service'),
    ('ts-order-other-service', 'ts-station-service'),
    ('ts-order-service', 'ts-station-service'),
    ('ts-order-service', 'ts-assurance-service'),
    ('ts-auth-service', 'ts-verification-code-service'),
]

STATS_TOP_K = 40

DEFAULT_SRC = '/home/zhangll24/RCA_project/MSTGAD/data/TT-pre'
DEFAULT_RAW_DIR = '/home/zhangll24/RCA_project/Eadro/TT_Dataset/TT Dataset'
DEFAULT_SAVE_PATH = './data/TT-pre'
